name: jvm2json
version: '0.2.0'
author: Christian Gram Kalhauge
maintainer: "Christian Gram Kalhauge <chrg@dtu.dk>"
synopsis: A program for converting Java bytecode to and from json
license: BSD3
license-file: LICENSE
category: Language, Java, JVM
github: kalhauge/jvm2json

description: |
  A program for converting Java bytecode to and from json

ghc-options: 
- -Wall

extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - base >= 4.10 && < 4.18
  - aeson
  - bytestring
  - conedec >= 0.2.0
  - cones 
  - containers
  - jvm-binary
  - jvmhs >= 0.2.0 && <= 0.2.0
  - unordered-containers
  - optparse-applicative
  - prettyprinter

library:
  source-dirs: src

executables:
  jvm2json:
    source-dirs: bin
    main: Main.hs
    dependencies:
      - jvm2json

tests:
  jvm2json-test:
    source-dirs: test/src
    main: Main.hs
    dependencies:
      - jvm2json
      - tasty
      - tasty-golden
      - text
      - typed-process
      - filepath
      - directory
