resolver: lts-23.28
packages:
- .
extra-deps:
- fgl-visualize-0.1.0.1
- git: https://github.com/ucla-pls/jvm-binary
  commit: be51cc4c8ae75eb7caec4949774c08b7c12d460e
- git: https://github.com/ucla-pls/jvmhs
  commit: 0542648d411c0b8000657590a431e697b95729c3
- git: https://github.com/kalhauge/cones
  commit: 669e58c31dddfe3d17f303ce65c67cb94abed5b4
  subdirs:
  - cones
  - conedec
