resolver: lts-20.26
packages:
- .
extra-deps:
- fgl-visualize-0.1.0.1
- git: https://github.com/ucla-pls/jvm-binary
  commit: 6c90146ebfb473b1eb699801431bdd5911eb4683
- git: https://github.com/ucla-pls/jvmhs
  commit: ea2fae5db242af8c3ad025ecb01cd721e12f04de
- git: https://github.com/kalhauge/cones
  commit: 69d30f009e61abb603da03f0d5be40352378fdff
  subdirs:
  - cones
  - conedec
